### ISSUE TITLE
Come cambiare css header e footer

### ISSUE THREAD

**Issue by matteobregola** [ProgWeb17Unitn/Tum4World#14]
Dato che simpatizzante, aderente ed admin hanno un css specifico, come facciamo a cambiare il css di header e footer dato che i css sono inclusi nell'html e non nei jsp?

**Comment by rrikiliba** [comment]
## possibili soluzioni

(trovate al volo)

- importare il css non nell'html ma nei JSP delle pagine che usano header e footer (tutte) (brutto)
- possibile includere il css direttamente da un - altro css, secondo lo schema:

in JSP, ho la mia import condizionale, basata sul cookie che mi salva il tipo di utente come avevamo discusso. Admin = css1, utente = css2 etc

questa decide, in ciascuna pagina, quale css dei colori importare 

all'interno del css di ciascun tema, aggiungiamo 

@import url("{themehere}Header.css")

nei prossimi giorni provo a vedere se e come funziona
