### ISSUE TITLE
Hamburger pt.245

### ISSUE THREAD

**Issue by matteobregola** [ProgWeb17Unitn/Tum4World#19]
quando avvi l'applicazione compare per un attimo la foglia :). ed anche quando cambi link

**Comment by rrikiliba** [comment]
my brother I'm Christ quella è una piuma non una foglia 💀

**Comment by matteobregola** [comment]
AH, HAHAHAHAHAH, ao era mezzanotte, già tento che non abbia visto un
pappagallo

Il mar 4 lug 2023, 07:32 rrikiliba ***@***.***> ha scritto:

**Comment by rrikiliba** [comment]
**Dovrebbe** essere fixato nell'ultimo commit
